### ISSUE TITLE
Metrics endpoint not available

### ISSUE THREAD

**Issue by arnefromsa** [aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework#19]
Goodday.

I've tried to utilize the Metrics endpoint which accoding to the documentation should be under {pipelines_base_url}/metrics , however this is not present.

I imported the swagger file into postman to make it a bit easier to execute, but still getting the following jsons return :

`
{
    "message": "Route POST:/metrics not found",
    "error": "Not Found",
    "statusCode": 404
}
`

**Comment by arnefromsa** [comment]
This was due to the swagger import not setting the Accept-Version, which should be set to 1.0.0. 

After adding this to the header it routes correctly.  

Still would be nice to have this part of the original postman collection in the project.

**Comment by johnrotach** [comment]
Thanks for raising as an issue @arnefromsa. We're tracking this and will update here when released.

**Comment by johnrotach** [comment]
Resolved in [release v.1.9.0](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework/releases/tag/v1.9.0). Closing issue.
