### ISSUE TITLE
SIF v1.8.0 Audit Bug 

### ISSUE THREAD

**Issue by davejohnsen2** [aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework#21]
Bug Description: Inability to access the audit reports from pipeline executions
Endpoint: {pipelineExecutionApi}/pipelines/{pipelineId}/executions/{executionId}/generateAuditExportUrl
Issues: 
1)	Audit report is not generated (SIF lambda is missing permissions to interact with SIF sqs queue). Status: Added temporary hack to override SIF lambda function permissions to give permissions 
2)	After fix from 1 above, audit report is generated but has no data. Status: blocked

**Comment by johnrotach** [comment]
Resolved in [release v.1.9.0](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework/releases/tag/v1.9.0). Closing issue.
