### ISSUE TITLE
Slow Pipeline Execution Time

### ISSUE THREAD

**Issue by davejohnsen2** [aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework#23]
For web or mobile application usage, the total time for a basic pipeline execution for a single activity (or small numbers of activities) should be < 5 s. Results should include calculated values and metric values. Any steps outside of the basic task can be performed async

Example 
inputs: myinput=5
transform: myoutput = myinput*2, metric ["mymetric"]
outputs: myoutput=10

metricTotals: mymetric=10

**Comment by boardthatpowder** [comment]
Hi David, to clarify the ask....  metrics are global, they span pipelines and executions. So when you refer to returning `mymetric=10` above, are you wanting just what this execution contributed to `mymetric`, i.e. the sum of `myoutput` in your example, or are you wanting the revised global value of `mymetric`?

**Comment by johnrotach** [comment]
Resolved in [release v.1.9.0](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework/releases/tag/v1.9.0). Closing issue.
